
name: LabDemo.MinimalApi.BuildByStages
run-name: ${{ github.actor }} is experimenting with GitHub actions 🚀
on: [workflow_dispatch, pull_request, push]

env:    
    PUBLISH_ARTIFACT_NAME: publish
    PUBLISH_PATH: publish

jobs:
  #============================================================
  #  AZURE DEPLOY
  #
  #  Requires both an app service and an API service pre-configured, and the names must
  #  match

  deploy_azure:
    name: Manually deploy to Azure
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    # this relies on GitHub settings for the production environment
    # that require manual approval before deployment

    environment:
      name: production

    needs: [publish]    
    steps:

    - name: Download artifact from publish job
      uses: actions/download-artifact@v3
      with:
        name: ${{env.PUBLISH_ARTIFACT_NAME}}
        path: ${{env.PUBLISH_PATH}}

    - name: Validate artifact presence
      run: |
        if [ -z "$(ls -A ${{env.PUBLISH_PATH}})" ]; then
           exit 1
        fi

    - name: Validate directory state
      run: |
        du -sh ./*

    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'LabDemo-MinimalApi-Code'
        slot-name: 'Production'
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_FEB370F5C81A4C1EBA8D302EC1CB0084 }}
        package: ./publish