# Barebones of continuous integration in stages

# Much, much room for optimization and bringing closer to the real world

name: LabDemo.MinimalApi.BuildByStages
run-name: ${{ github.actor }} is experimenting with GitHub actions 🚀
on: [push]

env:
    SOLUTION: LabDemo.MinimalApi
    PROJECT: LabDemo.MinimalApi

jobs:
  build:
    name: Build the API

    runs-on: windows-latest

    steps:       
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Inputs
      run: |
        echo "SOLUTION = " $SOLUTION
        echo "PROJECT = " PROJECT
        echo "Running in..."
        pwd
        echo "Total storage consumption before job:" 
        du -sh /* | sort -h

    - name: Build the project
      run: |
        dotnet $PROJECT
        dotnet build

    - name: Metrics
      run: |
        echo "Total storage consumption after job:" 
        du -sh /* | sort -h
        

  test:
    name: Black-box test the API

    runs-on: windows-latest

    env:
      TEST_PROJECT: LabDemo.MinimalApi.Tests

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Inputs
      run: |
        echo "TEST_PROJECT = " PROJECT
        echo "Running in..."
        pwd
        echo "Total storage consumption before job:" 
        du -sh /* | sort -h

    - name: Run the black box tests
      run: |
        pwd
        cd ../$TEST_PROJECT
        pwd
        cd $TEST_PROJECT
        dotnet test

    - name: Metrics
      run: |
        echo "Total storage consumption after job:" 
        du -sh /* | sort -h
