# Barebones of continuous integration in stages

# Much, much room for optimization and bringing closer to the real world

name: LabDemo.MinimalApi.BuildByStages
run-name: ${{ github.actor }} is experimenting with GitHub actions 🚀
on: [push]

env:
    _SOLUTION: LabDemo.MinimalApi
    _PROJECT: LabDemo.MinimalApi
    _TEST_PROJECT: LabDemo.MinimalApi.Tests

jobs:
  build:
    name: Build the API

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Build the project
      run: |
        pwd
        dotnet $_PROJECT
        dotnet build

  test:
    name: Black-box test the API

    runs-on: windows-latest

    env:
      TEST_PROJECT: LabDemo.MinimalApi.Tests

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Run the black box tests
      run: |
        pwd
        cd ../$TEST_PROJECT
        pwd
        cd $TEST_PROJECT
        dotnet test