name: LabDemo.MinimalApi.BuildByStages
run-name: ${{ github.actor }} is experimenting with GitHub actions 🚀
on: [push]
jobs:
  build:
    runs-on: windows-latest

    env:
      SOLUTION: LabDemo.MinimalApi
      PROJECT: LabDemo.MinimalApi
      TEST_PROJECT: LabDemo.MinimalApi.Tests

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x