name: LabDemo.MinimalApi.BuildByStages
run-name: ${{ github.actor }} is experimenting with GitHub actions 🚀
on: [push]
jobs:
  MakeLabDemoMinimalApi:
    runs-on: ubuntu-latest
    steps:
      - name: build
        env:
          PROJECT: LabDemo.MinimalApi
        uses: actions/checkout@v3
        run: |
          echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
          echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
          echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
          ls ${{ github.workspace }}