# Barebones of continuous integration in stages

# Much, much room for optimization and bringing closer to the real world

name: LabDemo.MinimalApi.BuildByStages
run-name: ${{ github.actor }} is experimenting with GitHub actions 🚀
on: [push]

env:
    SOLUTION: LabDemo.MinimalApi
    PROJECT: LabDemo.MinimalApi

jobs:

  #============================================================
  #  BUILD STAGE
  #
  #  IN-PROGRESS: Implementing caching 
  #

  build:
    name: Build API

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['7.x.x' ]

    steps:       
    - name: Checkout
      uses: actions/checkout@v3

    # TODO: only for debug
    - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ matrix.dotnet-version }}

    - name: Before
#      working-directory: .
      run: |
        echo "SOLUTION = $SOLUTION"
        echo "PROJECT = $PROJECT"
        echo "Total solution storage consumption before job for ${PWD}:" 
        du -sh ./*


    # The custom location of nuget packages is in place for later optimizations if
    # dependencies grow, when runner storage or job speeds become a concern

    # The custom build location is cached for use by the test job

    - name: Build the project
      run: |        
        cd $PROJECT
        dotnet restore --packages ../nuget
        dotnet build -c Release --no-incremental --no-restore --source ../nuget -o ../build

   # The nuget packages can be cached for another workflow run, for optimization
   # In this case, the app has minimal dependencies, so not important to cache

    - name: Pass the build on to other jobs
      uses: actions/upload-artifact@v3
      with:
        name: api-build-output
        path: ./build
        retention-days: 1

    - name: After
      run: |
        echo "Total solution storage consumption before job for ${PWD}:" 
        du -sh ./*
        
  #============================================================
  #  TEST STAGE

  test:
    name: API Black-Box Testing

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    runs-on: ubuntu-latest

    strategy:
      matrix:
        dotnet-version: ['7.x.x' ]

    needs: [build]    
    
    env:
      TEST_PROJECT: LabDemo.MinimalApi.Tests

    steps:

    - name: Checkout
      uses: actions/checkout@v3
      
    # TODO: only for debug
    - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ matrix.dotnet-version }}

    - name: Before
      run: |
        echo "SOLUTION = $SOLUTION"
        echo "TEST_PROJECT = $TEST_PROJECT"
        echo "Running in ${PWD}"
        echo "Total solution storage consumption before job for ${PWD}:" 
        du -sh ./*
        
    - name: Download api build artifacts for speed optimization
      uses: actions/download-artifact@v3
      with: 
        name: api-build-output
        path: ../build

    - name: Check artifact download
      run: pwd; ls; ls ../build

    - name: Run the black box tests
      run: |
        cd $TEST_PROJECT
        dotnet test -c Release -o ../build

    - name: After
      run: |
        echo "Total solution storage consumption before job for ${PWD}:" 
        du -sh ./*

  #============================================================
  #  PUBLISH STAGE

  publish:
    name: Publish the API

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash
#        working-directory: .

    runs-on: ubuntu-latest

    strategy:
      matrix:
        dotnet-version: ['7.x.x' ]

    needs: [build, test]    
        
    steps:

      - uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.x'
          include-prerelease: true

      - name: Download api build artifacts for speed optimization
        uses: actions/download-artifact@v3
        with: 
          name: api-build-output
          path: ../build

      - name: Check artifact download
        run: pwd; ls; ls ../build

      # Optimized by using the output from the previous build job, which includes
      # not only the nuget dependencies, but the binaries for the api

      - name: Publish the API
        run: |
          pwd
          cd $PROJECT
          dotnet publish -c Release -o ../publish --source ../build

      - name: After
        run: |
          echo "Total solution storage consumption before job for ${PWD}:" 
          du -sh ./*

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: ${PROJECT}
          path: ../publish

  #============================================================
  #  DEPLOY STAGE

  deploy-azure:
    name: Deploy to Azure

    defaults:
      run:
        shell: bash
#        working-directory: .

    runs-on: ubuntu-latest

    needs: [build, test]    

    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: ${PROJECT}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'LabDemo-MinimalApi-Code'
          slot-name: 'production'
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_a3c3d11e8d764bfdbf88856aa7a173c4 }}
          package: .